CREATE TABLE IF NOT EXISTS fields (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, heading TEXT NOT NULL, planted TEXT, lat REAL, lng REAL, updated_by TEXT, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS activity (id INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT DEFAULT CURRENT_TIMESTAMP, user TEXT, action TEXT, detail TEXT);
